spring:
  profiles:
    active: "prod"
    
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:formation
    username: sa
    password: changeme
    driverClassName: org.h2.Driver
server:
  port: 19090
info :
  app :
    name: Formation Microservices
    description: Gestion des clients avec Spring boot
    version: 1.0.0

---
spring:
  profiles: prod
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update     
  datasource:
    url: jdbc:postgresql://postgres:5432/sales
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 9090
info :
  app :
    name: Formation Microservices
    description: Gestion des clients avec Spring boot
    version: 1.0.0